[project]
name = "molml_mcp"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "fastmcp==2.11.0",
    "rdkit>=2025.9.1",
    "numpy",
    "scikit-learn",
    "pandas",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]